laravel/routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');


Route::resource('user', 'UserController');
Route::resource('container', 'ContainerController');

Route::get('token/index', 'ApiTokenController@index')->name('token.index');
Route::get('token/store', 'ApiTokenController@store')->name('token.store');

laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Container;

Route::get('/', function () {
    $view = view('overview');
    $view->containers = Container::orderBy('current_volume', 'DESC')->get();

    return $view;
});
Auth::routes();

laravel/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

laravel/app/Http/Controllers/cms/HomeController.php
<?php namespace App\Http\Controllers\Admin;


use App\Container;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{

    public function index()
    {
        $view = view('cms.index');
        $view->title = 'Dashboard';
        $view->containers = Container::orderBy('current_volume', 'DESC')->get();

        return $view;
    }
}

laravel/app/Http/Controllers/cms/UserController.php
<?php namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\UserRequest;
use App\User;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public function index()
    {
        $view = view('cms.user.index');
        $view->title = 'Administrators';
        $view->users = User::all();
        return $view;
    }

    public function create()
    {
        $view = view('cms.user.create');
        $view->title = 'Administrator toevoegen';
        return $view;
    }

    public function store(UserRequest $request)
    {
        $input = $request->all();
        $input['password'] = Hash::make($input['password']);
        User::create($input);
        return redirect()->route('admin.user.index')->withMessage('Administrator aangemaakt');
    }


    public function edit(User $user)
    {
       $view = view('cms.user.edit');
       $view->user = $user;
       $view->title = 'Administrator bewerken';
       return $view;
    }

    public function update(UserRequest $request, User $user)
    {
        $input = $request->except('user_id');
        $input['password'] = Hash::make($input['password']);
        $user->update($input);
        return redirect()->route('admin.user.edit', $user->id)->withMessage('Administrator is bijgewerkt');
    }

    public function destroy(User $user)
    {
        $name = $user->name;
        $user->delete();
        return redirect()->route('admin.user.index')->withMessage('Administrator '.$name.' is verwijderd');
    }
}

laravel/resources/views/cms/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center"
         style="min-height: 200px; background-size: cover; background-position: center top;">
        <!-- Mask -->
        <span class="mask bg-gradient-default opacity-8"></span>
        <!-- Header container -->
        <div class="container-fluid align-items-center">
            <div class="row mb-4">
                <div class="col-lg-3">
                    <div class="card card-stats">
                        <div class="card-body">
                            <div class="row">
                                <div class="col">
                                    <h5 class="card-title text-uppercase text-muted mb-0">Totaal Aantal Containers:</h5>
                                    <span class="h2 font-weight-bold mb-0">{{ $containers->count() }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12">
                <div class="card bg-secondary card-profile shadow mb-5">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-lg-6">
                                <h3 class="m-0 p-0">Containers</h3>
                            </div>
                            {{--                            <div class="col-lg-6">--}}
                            {{--                                <a href="{{ route('admin.container.create') }}" style="float: right" class="btn btn-sm btn-primary">--}}
                            {{--                                    Container toevoegen--}}
                            {{--                                </a>--}}
                            {{--                            </div>--}}
                        </div>
                    </div>
                    <div class="table-responsive">
                        <div>
                            <table class="table align-items-center">
                                <thead class="thead-light">
                                <tr>
                                    <th scope="col">
                                        Coordinaten
                                    </th>
{{--                                    <th scope="col">--}}
{{--                                        Status--}}
{{--                                    </th>--}}
                                    <th scope="col">
                                        Volume (%)
                                    </th>
                                    <th scope="col">
                                        ID
                                    </th>
                                    <th scope="col">
                                        Opties
                                    </th>
                                </tr>
                                </thead>
                                <tbody class="list">
                                @forelse($containers as $container)
                                <tr class="@if($container->current_volume >= $container->max_volume) bg-red text-white @endif">
                                    <td>
                                        <span class="badge badge-dot mr-4">
                                            {{$container->coordinates}}
                                        </span>
                                    </td>
{{--                                    <td>--}}
{{--                                        <span class="badge badge-dot mr-4">--}}
{{--                                            <i class="bg-warning"></i> pending--}}
{{--                                        </span>--}}
{{--                                    </td>--}}
                                    <td class="completion">
                                        <div class="d-flex align-items-center">
                                            <span class="mr-2">{{$container->current_volume}}%</span>
                                            <div>
                                                <div class="progress">
                                                    <div class="progress-bar bg-warning" role="progressbar"
                                                         aria-valuenow="60" aria-valuemin="0"
                                                         aria-valuemax="100" style="width: {{$container->current_volume}}%;"></div>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                            {{ $container->id }}
                                    </td>
                                    <td>
                                        <a class="btn btn-sm btn-primary"
                                           target="_blank"
                                           href="http://www.google.com/maps/place/{{$container->coordinates}}">
                                            Locatie
                                        </a>
                                        <a class="btn btn-sm btn-primary"
                                           href="{{ route('admin.container.edit', $container->id) }}">Wijzigen
                                        </a>
                                    </td>
                                </tr>
                                    @empty
                                    <tr>
                                        <td>
                                            Geen Containers
                                        </td>
                                    </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

laravel/resources/views/cms/user/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center"
         style="min-height: 200px; background-size: cover; background-position: center top;">
        <span class="mask bg-gradient-default opacity-8"></span>
        <div class="container-fluid d-flex align-items-center">
            <div class="row">
                <div class="col-lg-12 col-md-10">
                    <h1 class="display-2 text-white">{{ $title }}</h1>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12">
                @include('layouts.notifications')

                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-12">
                                <h3 class="mb-0">{{ $title }}</h3>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        {{ Form::open(['route' =>'admin.user.store']) }}
                        @include('cms.user.form')
                        <button type="submit" class="btn btn-sm btn-primary pull-right">Toevoegen</button>
                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

laravel/resources/views/cms/user/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center"
         style="min-height: 200px; background-size: cover; background-position: center top;">
        <span class="mask bg-gradient-default opacity-8"></span>
        <div class="container-fluid d-flex align-items-center">
            <div class="row">
                <div class="col-lg-12 col-md-10">
                    <h1 class="display-2 text-white">{{ $title }}</h1>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12">
                @include('layouts.notifications')

                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-6">
                                <h3 class="mb-0">{{ $title }}</h3>
                            </div>
{{--                            <div class="col-6">--}}
{{--                                <button type="button" class="btn btn-sm btn-danger float-right" data-toggle="modal" data-target="#deleteModal">Administrator verwijderen</button>--}}
{{--                            </div>--}}
                        </div>
                    </div>
                    <div class="card-body">
                        {{ Form::model($user,['route' =>['admin.user.update', $user->id], 'method' => 'PUT']) }}
                        {{ Form::hidden('user_id', $user->id) }}
                        @include('cms.user.form')
                        <button type="submit" class="btn btn-sm btn-primary">Wijzigingen opslaan</button>
                        {{ Form::close() }}

                        {{ Form::open(['route' => ['admin.user.destroy' ,$user->id], 'method' => 'DELETE', 'id' => 'delete']) }}
                        {{ Form::close() }}
                        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                             aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Weet u zeker dat u {{ $user->name }} wil verwijderen?</h5>
                                    </div>
                                    <div class="modal-footer" style="color: white;">
                                        <a class="btn btn-sm btn-success" onclick="$('#delete').submit()">Ja</a>
                                        <a class="btn btn-sm btn-danger" data-dismiss="modal">Nee</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

laravel/resources/views/cms/user/form.blade.php
<div class="form-group">
    {{ Form::text('name', old('name'), ['class' => 'form-control', 'id'=> 'nameBox', 'placeholder'=>'Naam']) }}
</div>
<div class="form-group">
    {{ Form::text('email', old('email'), ['class' => 'form-control', 'placeholder'=>'Email']) }}
</div>
<div class="form-group">
    <input type="password" name="password" class="form-control" placeholder="Wachtwoord" >
</div>
<div class="form-group">
    <input type="password" name="password_confirmation" class="form-control" placeholder="Wachtwoord bevestigen" >
</div>

laravel/resources/views/cms/user/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center"
         style="min-height: 200px; background-size: cover; background-position: center top;">
        <span class="mask bg-gradient-default opacity-8"></span>
        <div class="container-fluid d-flex align-items-center">
            <div class="row">
                <div class="col-lg-12 col-md-10">
                    <h1 class="display-2 text-white">{{ $title }}</h1>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12">
                @include('layouts.notifications')
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-md-8">
                                <h3 class="mb-0">{{ $title }}</h3>
                            </div>
                            <div class="col-md-4 text-right">
                                <a href="{{ route('admin.user.create') }}" class="btn btn-sm btn-primary">Nieuwe
                                    Administrator</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover align-items-center">
                                <thead>
                                <tr>
                                    <th>Naam</th>
                                    <th>Email</th>
                                </tr>
                                </thead>
                                <tbody class="clickable">
                                @foreach($users as $user)
                                    <tr data-url="{{ route('admin.user.edit', $user->id) }}">
                                        <td width="40%">{{ $user->name }}</td>
                                        <td width="40%">{{ $user->email }}</td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

laravel/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ $title }}</title>
    {{--    <link href="{{ asset('favicon.ico') }}" rel="icon" type="image/png">--}}
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    {!! HTML::style('argon-dashboard-master/assets/vendor/nucleo/css/nucleo.css') !!}
    {!! HTML::style('argon-dashboard-master/assets/vendor/@fortawesome/fontawesome-free/css/all.min.css') !!}
    {!! HTML::style('argon-dashboard-master/assets/css/argon.min.css') !!}
    {!! HTML::style('css/app.css') !!}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css"
          integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    @yield('head')
</head>
<body id="app">
{{--@if(Route::currentRouteName() == 'admin.page.edit')--}}
    {{--@include('layouts.page_edit_side')--}}
    {{--@include('templates.default.index')--}}
{{--@else--}}
    @include('layouts.side_nav')
    <div class="main-content">
        @include('layouts.upper_nav')
        @yield('content')
    </div>
{{--@endif--}}
{!! HTML::script('argon-dashboard-master/assets/vendor/jquery/dist/jquery.min.js') !!}
{!! HTML::script('argon-dashboard-master/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js') !!}
{!! HTML::script('argon-dashboard-master/assets/js/argon.min.js') !!}
<script>
    $('.clickable tr').click(function () {
        window.location.href = $(this).data('url');
    });
</script>

@yield('script')

</body>
</html>

laravel/resources/views/layouts/notifications.blade.php
@if(Session::has('message'))
    <div class="alert alert-success alert-dismissible fade show mt-2" role="alert">
            <span class="alert-inner--text"><i class="ni ni-air-baloon"></i> {{ Session::get('message') }}</span><br>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif
@if(!$errors->isEmpty())
<div class="alert alert-danger alert-dismissible fade show mt-2" role="alert">
    @foreach($errors->all() as $error)
        <span class="alert-inner--text"><i class="ni ni-air-baloon"></i> {{ $error }}</span><br>
    @endforeach
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
@endif

laravel/resources/views/layouts/page_edit_side.blade.php
<nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
    <div class="container-fluid">
        <!-- Toggler -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand pt-0" href="#">
            {{ $page->title }}
        </a>
        <ul class="nav align-items-center d-md-none">
            <li class="nav-item dropdown">
                <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <div class="media align-items-center">
            <span class="avatar avatar-sm rounded-circle">
              <img alt="Image placeholder" src="{{ asset('argon-dashboard-master/assets/img/theme/team-1-800x800.jpg') }}">
            </span>
                    </div>
                </a>
            </li>
        </ul>
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
            <!-- Collapse header -->
            <div class="navbar-collapse-header d-md-none">
                <div class="row">
                    <div class="col-6 collapse-brand">
                        <a href="">
                            {{ $page->title }}
                        </a>
                    </div>
                    <div class="col-6 collapse-close">
                        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                            <span></span>
                            <span></span>
                        </button>
                    </div>
                </div>
            </div>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link @if(Request::is('admin')) active @endif" href="{{ route('admin.home') }}">
                        <i class="ni ni-tv-2 text-primary"></i> Dashboard
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

laravel/resources/views/layouts/side_nav.blade.php
<nav class="navbar navbar-vertical fixed-left navbar-expand-md bg-gradient-secondary" id="sidenav-main">
    <div class="container-fluid">
        <!-- Toggler -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main"
                aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand pt-0" href="#">
            <img style="max-height: 4.7rem" src="{{ asset('images/logo.png') }}" class="navbar-brand-img" alt="...">
        </a>
        <ul class="nav align-items-center d-md-none">
            <li class="nav-item dropdown">
                <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                   aria-expanded="false">
                    <div class="media align-items-center">
{{--            <span class="avatar avatar-sm rounded-circle">--}}
{{--              <img alt="Image placeholder"--}}
{{--                   src="{{ asset('argon-dashboard-master/assets/img/theme/team-1-800x800.jpg') }}">--}}
{{--            </span>--}}
                    </div>
                </a>
            </li>
        </ul>
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
            <!-- Collapse header -->
            <div class="navbar-collapse-header d-md-none">
                <div class="row">
                    <div class="col-6 collapse-brand">
                        <a href="#">
                            <img src="{{ asset('images/logo.png') }}">
                        </a>
                    </div>
                    <div class="col-6 collapse-close">
                        <button type="button" class="navbar-toggler" data-toggle="collapse"
                                data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false"
                                aria-label="Toggle sidenav">
                            <span></span>
                            <span></span>
                        </button>
                    </div>
                </div>
            </div>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link @if(Request::is('admin')) active @endif" href="{{ route('admin.home') }}">
                        <i class="ni ni-tv-2 text-primary"></i> Dashboard
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link @if(Request::is('admin/user*')) active @endif"
                       href="{{ route('admin.user.index') }}">
                        <i class="ni ni-single-02 text-primary"></i> Administrators
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link @if(Request::is('admin/token*')) active @endif"
                       href="{{ route('admin.token.index') }}">
                        <i class="ni ni-send text-primary"></i> Api Tokens
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

laravel/resources/views/layouts/upper_nav.blade.php
<nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
    <div class="container-fluid">
        <!-- Brand -->
        <a class="h4 mb-0 text-white text-uppercase d-none d-lg-inline-block" href="#"></a>

        <ul class="navbar-nav align-items-center d-none d-md-flex">
            <li class="nav-item dropdown">
                <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                   aria-expanded="false">
                    <div class="media align-items-center">
{{--                <span class="avatar avatar-sm rounded-circle">--}}
{{--                  <img alt="Image placeholder" src="{{ asset('argon-dashboard-master/assets/img/theme/team-1-800x800.jpg') }}">--}}
{{--                </span>--}}
                        <div class="media-body ml-2 d-none d-lg-block">
                            <span class="mb-0 text-sm  font-weight-bold">{{ Auth::user()->name }}</span>
                        </div>
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
                    <div class="dropdown-divider"></div>
                    {{ Form::open(['route' => 'logout', 'id'=>'logout']) }}
                    {{ Form::close() }}
                    <a onclick="$('#logout').submit()" href="#" class="dropdown-item">
                        <i class="ni ni-user-run"></i>
                        <span>Logout</span>
                    </a>
                </div>
            </li>
        </ul>
    </div>
</nav>